### PR TITLE
Retrieve CrystalDecisions and CrystalReports library references from NuGet

### PR DESCRIPTION
**Pull request by ascire**
You still need to bring your own DLLs, but at least now it can build without installing CrystalDecisions.

### CODE REVIEW

**Comment by ascire** [comment]
Resolves #34

**Comment by ajryan** [comment]
Looks good! What do you mean "bring your own DLLs?" -- like on the machine running the app?

**Comment by ascire** [comment]
You still have to install the Crystal Reports libraries separately.  Copy Local is disabled for most of the DLLs in the NuGet packages.

The packages were provided by a third party not affiliated with SAP, so I don't know if they can be trusted for anything more than an API reference anyway.

**Comment by ascire** [comment]
This is not looking so good with further testing.

**Pull request closed without merging**
